name: Auto Build Bicep

on:
  push:
    branches:
      - master
    paths:
      - '!tests/**'
      - '**.bicep'
      - '!**azuredeploy.json'

jobs:
  main:
    name: Auto Build Bicep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Build main.bicep -> azuredeploy.json
        uses: Azure/cli@v1
        with:
          # Specify the script here
          inlineScript: |
            # Get path of last file checked in
            cd $GITHUB_WORKSPACE
            LAST_PATHS=$( git log --pretty="" --name-only -n 100 origin/master... -- | fgrep -v ".github")
            
            for LAST_PATH in $LAST_PATHS
            do
            
              echo $LAST_PATH: Last file modified.

              # Look for the main template file in this file's path or parents
              SAMPLEFOLDER_PATH=$( dirname "$LAST_PATH" )
              echo $SAMPLEFOLDER_PATH: Last folder modified

              TESTFOLDER_PATH=$SAMPLEFOLDER_PATH
              FOUNDFOLDER_PATH=
              while [ "$TESTFOLDER_PATH" != "." ]
              do
                echo "Looking for main template in $TESTFOLDER_PATH"
                MAINBICEP_PATH=$TESTFOLDER_PATH/main.bicep
                AZDEPLOYJSON_PATH=$TESTFOLDER_PATH/azuredeploy.json

                if [ -f $MAINBICEP_PATH ]; then
                  FOUNDFOLDER_PATH=$TESTFOLDER_PATH
                  echo Found main template in $FOUNDFOLDER_PATH

                  echo Running: az bicep build --file $MAINBICEP_PATH --outfile $AZDEPLOYJSON_PATH
                  az bicep build --file $MAINBICEP_PATH --outfile $AZDEPLOYJSON_PATH
                fi

                TESTFOLDER_PATH=$SAMPLEFOLDER_PATH
              done
            done

            if [ ! $FOUNDFOLDER_PATH ]; then
                echo "Could not find main.bicep or azdeploy.json in folders." 1>&2
                exit 1
            fi          

      - name: Commit changes
        if: always()
        run: |
          git config --global user.email "azure-quickstart-templates@noreply.github.com"
          git config --global user.name "azure-quickstart-templates Automation"

          git add .

          if ! git diff-index --quiet HEAD --; then
            git commit -m "Automatic fixes" --amend
            git push origin ${GITHUB_REF##*/} --force-with-lease
          fi
